import type { HeroDefinition } from "@jev-game/game";

export const firebrand: HeroDefinition = {
  id: "firebrand",
  name: "Firebrand",
  title: "The fuse",
  description:
    "A backline mage who lights a short fuse on the most crowded enemy. It panics into its own team, spreading fire, then explodes.",
  role: "backline",
  draftable: true,
  maxHp: 480,
  moveUnitsPerSecond: 12,
  bodyRadiusUnits: 3,
  maxMana: 70,
  startingMana: 30,
  attack: {
    kind: "projectile",
    name: "Firecracker",
    damage: 42,
    rangeUnits: 40,
    intervalTicks: 43,
    windupTicks: 12,
    unitsPerSecond: 60,
    splashRadiusUnits: 4,
    splashFraction: 0.5,
    allyHeal: 0,
  },
  signature: {
    kind: "short-fuse",
    name: "Short Fuse",
    description:
      "Sets the enemy with the most friends around it alight with a three-second fuse. It panics into its own team, setting them on fire, then explodes.",
    wants: ["grouped"],
    groupSize: 3,
    rangeUnits: 50,
    castTicks: 12,
    boltUnitsPerSecond: 70,
    fuseTicks: 90,
    panicMoveMultiplier: 1.6,
    burnDamagePerSecond: 16,
    burnTicks: 120,
    maxTouchHops: 2,
    blastRadiusUnits: 20,
    blastDamage: 180,
    blastLaunch: {
      centerRiseUnits: 14,
      edgeRiseUnits: 7,
      centerDistanceUnits: 36,
      edgeDistanceUnits: 20,
      bowlingDamage: 30,
    },
    hotPotatoScale: 1.5,
  },
  passive: null,
};
