import type { GemFit, UpgradeDefinition } from "@jev-game/game";

const ANY: GemFit[] = ["any"];

const DAMAGING: GemFit[] = ["damaging"];

export const gems: UpgradeDefinition[] = [
  {
    id: "gem-multistrike",
    name: "Multistrike",
    description: "The skill's strikes repeat twice more, 0.25 s apart, at 70%.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "multistrike", repeats: 2, delayTicks: 8, fraction: 0.7 },
    gemFits: ["attack"],
  },
  {
    id: "gem-multicast",
    name: "Multicast",
    description: "The spell casts again 0.3 s later at 70%.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "multicast", delayTicks: 9, fraction: 0.7 },
    gemFits: ["spell"],
  },
  {
    id: "gem-chain",
    name: "Chain",
    description: "The skill also hits 2 more nearby enemies at 60%. A bouncing skill bounces 2 more times instead, and a binding skill binds 2 more.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "chain", extraTargets: 2, fraction: 0.6, rangeUnits: 25 },
    gemFits: ["projectile", "strike", "target", "link"],
  },
  {
    id: "gem-fork",
    name: "Fork",
    description: "When the skill's projectile hits its first enemy, it splits into 2 more that each hit another enemy within 3 cells at 60%.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "fork", branches: 2, fraction: 0.6, rangeUnits: 30 },
    gemFits: ["projectile"],
  },
  {
    id: "gem-widen",
    name: "Widen",
    description: "The skill's area is 50% bigger.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "widen", radiusMultiplier: 1.5 },
    gemFits: ["area", "zone"],
  },
  {
    id: "gem-linger",
    name: "Linger",
    description:
      "The skill's area stays for 3 s and repeats 25% of its damage and healing every second. Ground it already leaves lasts 3 s longer, and a spin lasts 1 s longer.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "linger", durationTicks: 90, periodTicks: 30, fraction: 0.25, channelTicks: 30 },
    gemFits: ["area", "zone"],
  },
  {
    id: "gem-cast-on-crit",
    name: "Cast on Crit",
    description: "The skill casts whenever this hero crits. Recharge: 1 s.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "trigger", on: "crit", rechargeTicks: 30, fraction: 1 },
    gemFits: ANY,
  },
  {
    id: "gem-cast-on-kill",
    name: "Cast on Kill",
    description: "The skill casts whenever this hero kills an enemy.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "trigger", on: "kill", rechargeTicks: 0, fraction: 1 },
    gemFits: ANY,
  },
  {
    id: "gem-cast-when-damaged",
    name: "Cast when Damaged",
    description: "The skill casts each time this hero loses 15% of max HP to hits or HP costs. Poison and burn ticks don't count. Recharge: 1 s.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "trigger", on: "damaged", rechargeTicks: 30, fraction: 1, hpLossFraction: 0.15 },
    gemFits: ANY,
  },
  {
    id: "gem-cast-on-detonation",
    name: "Cast on Detonation",
    description: "The skill casts whenever an ally detonates a combo. Recharge: 2 s.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "trigger", on: "detonation", rechargeTicks: 60, fraction: 1 },
    gemFits: ANY,
  },
  {
    id: "gem-opener",
    name: "Opener",
    description: "The skill casts once for free about 2 s into every fight.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "trigger", on: "opener", rechargeTicks: 0, fraction: 1, atTick: 60 },
    gemFits: ANY,
  },
  {
    id: "gem-last-word",
    name: "Last Word",
    description: "When this hero dies, the skill casts once for free from where the hero fell.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "trigger", on: "last-word", rechargeTicks: 0, fraction: 1 },
    gemFits: ANY,
  },
  {
    id: "gem-overcharge",
    name: "Overcharge",
    description: "The skill is 75% stronger. Each cast costs this hero 8% of current HP.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "overcharge", effectMultiplier: 1.75, hpCostFraction: 0.08 },
    gemFits: ANY,
  },
  {
    id: "gem-leech",
    name: "Leech",
    description: "The skill heals its hero for 25% of the damage it deals.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "leech", fraction: 0.25 },
    gemFits: DAMAGING,
  },
  {
    id: "gem-haste",
    name: "Haste",
    description: "The skill recharges 25% faster. On an ultimate, it costs 25% less mana.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "haste", multiplier: 0.75 },
    gemFits: ANY,
  },
  {
    id: "gem-primer-staggered",
    name: "Primer: Staggered",
    description: "The skill also Staggers what it hits.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "primer", condition: "staggered" },
    gemFits: DAMAGING,
  },
  {
    id: "gem-primer-brittle",
    name: "Primer: Brittle",
    description: "The skill also makes what it hits Brittle.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "primer", condition: "brittle" },
    gemFits: DAMAGING,
  },
  {
    id: "gem-primer-disoriented",
    name: "Primer: Disoriented",
    description: "The skill also Disorients what it hits.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "primer", condition: "disoriented" },
    gemFits: DAMAGING,
  },
  {
    id: "gem-resonance",
    name: "Resonance",
    description: "The skill's hits count as Might, Arcana and Cunning at once, so they detonate any condition, including ones this hero applied.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "resonance" },
    gemFits: DAMAGING,
  },
  {
    id: "gem-split",
    name: "Split",
    description: "The skill summons 1 more unit and allows 1 more at once, but every summon from it has 30% less HP and damage.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "split", extraSummons: 1, strength: 0.7 },
    gemFits: ["summon"],
  },
  {
    id: "gem-empower",
    name: "Empower",
    description: "Summons from the skill have 40% more HP and damage.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "empower", strength: 1.4 },
    gemFits: ["summon"],
  },
  {
    id: "gem-barrage",
    name: "Barrage",
    description: "The skill also fires 2 more projectiles at other enemies in range, each at 60%.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "barrage", extraProjectiles: 2, fraction: 0.6 },
    gemFits: ["projectile"],
  },
  {
    id: "gem-pierce",
    name: "Pierce",
    description: "The projectile passes through every enemy in its path, hitting each one.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "pierce", widthUnits: 8 },
    gemFits: ["projectile"],
  },
  {
    id: "gem-concentrate",
    name: "Concentrate",
    description: "The area is 30% smaller and hits 40% harder.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "concentrate", radiusMultiplier: 0.7, damageMultiplier: 1.4 },
    gemFits: ["area"],
  },
  {
    id: "gem-vortex",
    name: "Vortex",
    description: "Pulls enemies near the area 1 cell towards its centre. On a channel, every pulse pulls.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "vortex", pullUnits: 10, reachMultiplier: 1.5 },
    gemFits: ["area", "channel"],
  },
  {
    id: "gem-cast-on-dash",
    name: "Cast on Dash",
    description: "The skill casts whenever this hero lands a dash, blink or leap. Recharge: 0.5 s.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "trigger", on: "dash", rechargeTicks: 15, fraction: 1 },
    gemFits: ["spell"],
  },
  {
    id: "gem-spellblade",
    name: "Spellblade",
    description: "Every 4th attack this hero makes casts the skill at 60%.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "trigger", on: "nth-attack", rechargeTicks: 0, fraction: 0.6, every: 4 },
    gemFits: ["spell"],
  },
  {
    id: "gem-ruthless",
    name: "Ruthless",
    description: "Every 3rd use of the skill deals 150% more and stuns every enemy it hits for 0.5 s.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "ruthless", every: 3, damageMultiplier: 2.5, stunTicks: 15 },
    gemFits: ANY,
  },
  {
    id: "gem-culling-strike",
    name: "Culling Strike",
    description: "The skill's hits kill enemies left below 12% HP.",
    category: "gem",
    maxStacks: 1,
    statModifiers: [],
    gem: { kind: "culling", threshold: 0.12 },
    gemFits: ["attack"],
  },
];
