import { BASIC_ATTACK_ABILITY, type AbilityDefinition, type UpgradeDefinition } from "@jev-game/game";

export const wardBellShield: AbilityDefinition = {
  id: "ward-bell",
  name: "Ward Bell",
  description: "Rings once, the first time the holder drops below 50% HP.",
  cooldownTicks: 1,
  targetPolicy: "self",
  range: 0,
  effects: [{ kind: "shield", amount: 0, maxHpFraction: 0.2, durationTicks: 120 }],
  tags: ["self"],
};

export const itemAbilities: AbilityDefinition[] = [wardBellShield];

export const items: UpgradeDefinition[] = [
  {
    id: "vitality-charm",
    name: "Vitality Charm",
    description: "+15% max HP.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [{ target: { kind: "max-hp" }, kind: "percent", value: 0.15 }],
  },
  {
    id: "whetstone",
    name: "Whetstone",
    description: "+12% damage.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [{ target: { kind: "damage" }, kind: "percent", value: 0.12 }],
  },
  {
    id: "quickblade-gloves",
    name: "Quickblade Gloves",
    description: "+12% attack speed.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [{ target: { kind: "basic-attack-cooldown" }, kind: "percent", value: 0.12 }],
  },
  {
    id: "mana-stone",
    name: "Mana Stone",
    description: "Start every fight with 30 mana.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [{ target: { kind: "starting-mana" }, kind: "flat", value: 30 }],
  },
  {
    id: "swift-boots",
    name: "Swift Boots",
    description: "+25% move speed and +8% attack speed.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [
      { target: { kind: "move-speed" }, kind: "percent", value: 0.25 },
      { target: { kind: "basic-attack-cooldown" }, kind: "percent", value: 0.08 },
    ],
  },
  {
    id: "ward-bell-item",
    name: "Ward Bell",
    description: "The first time the holder drops below 50% HP, it gains a shield worth 20% of max HP for 4 s.",
    category: "item",
    rarity: "common",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "hp-threshold", key: "ward-bell", fraction: 0.5, abilityId: wardBellShield.id }],
  },
  {
    id: "sparkflint",
    name: "Sparkflint",
    description: "Basic attacks set the target on fire: 1 Burn stack that deals 5 damage per second for 3 s, up to 3 stacks.",
    category: "item",
    rarity: "common",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [
      {
        kind: "every-nth-basic-attack",
        key: "sparkflint",
        n: 1,
        effects: [{ kind: "dot", dot: "burn", stacks: 1, damagePerStackPerSecond: 5, durationTicks: 90, maxStacks: 3 }],
      },
    ],
  },
  {
    id: "venom-vial",
    name: "Venom Vial",
    description: "Basic attacks add 1 Poison stack that deals 4 damage per second for 5 s, up to 5 stacks.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [
      {
        kind: "every-nth-basic-attack",
        key: "venom-vial",
        n: 1,
        effects: [{ kind: "dot", dot: "poison", stacks: 1, damagePerStackPerSecond: 4, durationTicks: 150, maxStacks: 5 }],
      },
    ],
  },
  {
    id: "sentinel-ward",
    name: "Sentinel Ward",
    description: "The first enemy that leaps or blinks within 2 cells of the holder is stunned for 1.5 s. Works once per fight.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "sentinel-ward", radiusUnits: 20, stunTicks: 45 }],
  },
  {
    id: "blight-ward",
    name: "Blight Ward",
    description: "Poison deals half damage to the holder, and Withering has no effect on it.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "blight-ward", poisonReduction: 0.5 }],
  },
  {
    id: "soul-lantern",
    name: "Soul Lantern",
    description: "When an allied hero falls, the holder gains all the mana that hero had left.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "soul-lantern" }],
  },
  {
    id: "soulbound-blade",
    name: "Soulbound Blade",
    description: "+60% damage. Downside: the holder loses 2% of max HP every second. This can't take the holder below 1 HP.",
    category: "item",
    rarity: "rare",
    cursed: true,
    maxStacks: 1,
    statModifiers: [{ target: { kind: "damage" }, kind: "percent", value: 0.6 }],
    grantsPassives: [{ kind: "soulbound", maxHpFractionPerSecond: 0.02 }],
  },
  {
    id: "glass-idol",
    name: "Glass Idol",
    description: "+25% damage and +20% attack speed. Downside: -30% max HP.",
    category: "item",
    rarity: "rare",
    cursed: true,
    maxStacks: 1,
    statModifiers: [
      { target: { kind: "damage" }, kind: "percent", value: 0.25 },
      { target: { kind: "basic-attack-cooldown" }, kind: "percent", value: 0.2 },
      { target: { kind: "max-hp" }, kind: "percent", value: -0.3 },
    ],
  },
  {
    id: "frost-brand",
    name: "Frost Brand",
    description: "Every 3rd basic attack makes the target Brittle.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [
      { kind: "every-nth-basic-attack", key: "frost-brand", n: 3, effects: [{ kind: "apply-condition", condition: "brittle" }] },
    ],
  },
  {
    id: "thunder-maul",
    name: "Thunder Maul",
    description: "Basic attacks count as Arcana, so they detonate allies' Staggered.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    abilityChanges: [{ abilityId: BASIC_ATTACK_ABILITY, setSchool: "arcana" }],
  },
  {
    id: "pocket-sand",
    name: "Pocket Sand",
    description: "The first hit on each enemy Disorients it.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [
      { kind: "first-hit-per-enemy", key: "pocket-sand", effects: [{ kind: "apply-condition", condition: "disoriented" }] },
    ],
  },
  {
    id: "vampiric-fang",
    name: "Vampiric Fang",
    description: "Heal for 15% of the damage you deal.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [{ target: { kind: "lifesteal" }, kind: "flat", value: 0.15 }],
  },
  {
    id: "brambleguard",
    name: "Brambleguard",
    description: "Can't be taunted. +5% armor.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [{ target: { kind: "armor" }, kind: "flat", value: 0.05 }],
    grantsPassives: [{ kind: "taunt-immune" }],
  },
  {
    id: "aegis",
    name: "Aegis",
    description: "Revive once at 20% HP.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "revive", hpFraction: 0.2 }],
  },
  {
    id: "hourglass",
    name: "Hourglass",
    description: "Right after the first signature of each fight, mana refills once.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "refill-after-first-signature" }],
  },
  {
    id: "kingmaker-banner",
    name: "Kingmaker Banner",
    description: "Every combo your team detonates gives every ally +4% attack speed for the rest of the fight.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "combo-rally", attackSpeedPerCombo: 0.04 }],
  },
  {
    id: "worldbreaker",
    name: "Worldbreaker",
    description: "Combos this hero detonates also hit every enemy within 2 cells.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "combo-splash", radiusUnits: 20 }],
  },
  {
    id: "prism-of-three",
    name: "Prism of Three",
    description: "This hero's hits count as Might, Arcana and Cunning at once, so they detonate any condition an ally applied.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "prism" }],
  },
  {
    id: "crown-of-echoes",
    name: "Crown of Echoes",
    description: "The Echo rune recasts at full strength, and Echo and Twincast recasts can crit and can apply and detonate conditions.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "crown-of-echoes" }],
  },
  {
    id: "blood-contract",
    name: "Blood Contract",
    description:
      "The signature costs 15% of max HP instead of mana and casts every 5 s while the hero is above 30% HP. Downside: the hero has no mana.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "blood-contract", hpFraction: 0.15, minHpFraction: 0.3, cooldownTicks: 150 }],
  },
  {
    id: "heart-of-the-swarm",
    name: "Heart of the Swarm",
    description: "Units this hero summons carry copies of its other items.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "heart-of-the-swarm" }],
  },
  {
    id: "obsidian-mirror",
    name: "Obsidian Mirror",
    description: "The first enemy signature cast at the holder is reflected: the holder casts it back at the caster instead. Works once per fight.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "obsidian-mirror" }],
  },
];
