import { ABILITY_SKILL, type AbilityDefinition, type UpgradeDefinition } from "@jev-game/game";

export const emberTrail: AbilityDefinition = {
  id: "ember-trail",
  name: "Ember Trail",
  description: "Fire left along a dash or leap. Enemies standing in it Burn.",
  hitType: "spell",
  cooldownTicks: 1,
  targetPolicy: "self",
  range: 0,
  effects: [],
  zone: {
    radiusUnits: 6,
    durationTicks: 60,
    periodTicks: 15,
    effects: [{ kind: "dot", dot: "burn", stacks: 1, damagePerStackPerSecond: 6, durationTicks: 90, maxStacks: 3 }],
  },
  tags: ["area"],
};

export const voidheartBlast: AbilityDefinition = {
  id: "voidheart",
  name: "Voidheart",
  description: "A slain enemy bursts, dealing a quarter of its max HP to every enemy within 1.5 cells. The body is used up.",
  hitType: "spell",
  cooldownTicks: 1,
  targetPolicy: "self",
  range: 0,
  area: { kind: "circle", center: "self", radiusUnits: 15 },
  effects: [{ kind: "damage", amount: 0, consumedMaxHpFraction: 0.25 }],
  canCrit: false,
  tags: ["area"],
};

export const itemAbilities: AbilityDefinition[] = [emberTrail, voidheartBlast];

export const items: UpgradeDefinition[] = [
  {
    id: "vitality-charm",
    name: "Vitality Charm",
    description: "+15% max HP.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [{ target: { kind: "max-hp" }, kind: "percent", value: 0.15 }],
  },
  {
    id: "whetstone",
    name: "Whetstone",
    description: "+12% attack damage.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [{ target: { kind: "attack-damage" }, kind: "percent", value: 0.12 }],
  },
  {
    id: "focus-crystal",
    name: "Focus Crystal",
    description: "+15% spell damage. Damage over time counts as spell damage.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [{ target: { kind: "spell-damage" }, kind: "percent", value: 0.15 }],
  },
  {
    id: "quickblade-gloves",
    name: "Quickblade Gloves",
    description: "+15% attack speed.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [{ target: { kind: "basic-attack-cooldown" }, kind: "percent", value: 0.15 }],
  },
  {
    id: "keen-edge",
    name: "Keen Edge",
    description: "+8% crit chance.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [{ target: { kind: "crit-chance" }, kind: "flat", value: 0.08 }],
  },
  {
    id: "mana-stone",
    name: "Mana Stone",
    description: "The ultimate charges 15% faster: attacks give 15% more mana.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [{ target: { kind: "mana-per-attack" }, kind: "percent", value: 0.15 }],
  },
  {
    id: "hourglass-shard",
    name: "Hourglass Shard",
    description: "The ability's cooldown is 12% shorter.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [{ target: { kind: "ability-cooldown", abilityId: ABILITY_SKILL }, kind: "percent", value: -0.12 }],
  },
  {
    id: "iron-plate",
    name: "Iron Plate",
    description: "+8% armor.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [{ target: { kind: "armor" }, kind: "flat", value: 0.08 }],
  },
  {
    id: "swift-boots",
    name: "Swift Boots",
    description: "+20% move speed, and dashes and leaps reach 1 cell further.",
    category: "item",
    rarity: "common",
    maxStacks: 3,
    statModifiers: [
      { target: { kind: "move-speed" }, kind: "percent", value: 0.2 },
      { target: { kind: "dash-reach" }, kind: "flat", value: 10 },
    ],
  },
  {
    id: "sparkflint",
    name: "Sparkflint",
    description: "Attacks set the target on fire: 1 Burn stack that deals 5 damage per second for 3 s, up to 3 stacks.",
    category: "item",
    rarity: "common",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [
      {
        kind: "every-nth-attack",
        key: "sparkflint",
        n: 1,
        effects: [{ kind: "dot", dot: "burn", stacks: 1, damagePerStackPerSecond: 5, durationTicks: 90, maxStacks: 3 }],
      },
    ],
  },
  {
    id: "venom-vial",
    name: "Venom Vial",
    description: "Attacks add 1 Poison stack that deals 4 damage per second for 5 s, up to 5 stacks.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [
      {
        kind: "every-nth-attack",
        key: "venom-vial",
        n: 1,
        effects: [{ kind: "dot", dot: "poison", stacks: 1, damagePerStackPerSecond: 4, durationTicks: 150, maxStacks: 5 }],
      },
    ],
  },
  {
    id: "sentinel-ward",
    name: "Sentinel Ward",
    description: "The first enemy that leaps or blinks within 2 cells of the holder is stunned for 1.5 s. Works once per fight.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "sentinel-ward", radiusUnits: 20, stunTicks: 45 }],
  },
  {
    id: "blight-ward",
    name: "Blight Ward",
    description: "Poison deals half damage to the holder, and Withering has no effect on it.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "blight-ward", poisonReduction: 0.5 }],
  },
  {
    id: "soulbound-blade",
    name: "Soulbound Blade",
    description: "+60% damage. Downside: the holder loses 2% of max HP every second. This can't take the holder below 1 HP.",
    category: "item",
    rarity: "rare",
    cursed: true,
    maxStacks: 1,
    statModifiers: [{ target: { kind: "damage" }, kind: "percent", value: 0.6 }],
    grantsPassives: [{ kind: "soulbound", maxHpFractionPerSecond: 0.02 }],
  },
  {
    id: "glass-idol",
    name: "Glass Idol",
    description: "+25% damage and +20% attack speed. Downside: -30% max HP.",
    category: "item",
    rarity: "rare",
    cursed: true,
    maxStacks: 1,
    statModifiers: [
      { target: { kind: "damage" }, kind: "percent", value: 0.25 },
      { target: { kind: "basic-attack-cooldown" }, kind: "percent", value: 0.2 },
      { target: { kind: "max-hp" }, kind: "percent", value: -0.3 },
    ],
  },
  {
    id: "frost-brand",
    name: "Frost Brand",
    description: "Every 3rd attack makes the target Brittle.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [
      { kind: "every-nth-attack", key: "frost-brand", n: 3, effects: [{ kind: "apply-condition", condition: "brittle" }] },
    ],
  },
  {
    id: "pocket-sand",
    name: "Pocket Sand",
    description: "The first hit on each enemy Disorients it.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [
      { kind: "first-hit-per-enemy", key: "pocket-sand", effects: [{ kind: "apply-condition", condition: "disoriented" }] },
    ],
  },
  {
    id: "skull-basher",
    name: "Skull Basher",
    description: "Every 4th attack stuns what it hits for 0.6 s.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "every-nth-attack", key: "skull-basher", n: 4, effects: [{ kind: "control", control: "stunned", durationTicks: 18 }] }],
  },
  {
    id: "spell-siphon",
    name: "Spell Siphon",
    description: "Each enemy your spells hit restores 5 mana, at most once per enemy each second.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "spell-siphon", mana: 5, perTargetTicks: 30 }],
  },
  {
    id: "ember-brand",
    name: "Ember Brand",
    description: "Dashes and leaps leave a trail of fire for 2 s. Enemies standing in it Burn.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "dash-trail", abilityId: emberTrail.id, spacingUnits: 10, maxZones: 3 }],
  },
  {
    id: "vampiric-fang",
    name: "Vampiric Fang",
    description: "Heal for 15% of the damage your attacks deal.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [{ target: { kind: "lifesteal" }, kind: "flat", value: 0.15 }],
  },
  {
    id: "brambleguard",
    name: "Brambleguard",
    description: "Can't be taunted. +5% armor.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [{ target: { kind: "armor" }, kind: "flat", value: 0.05 }],
    grantsPassives: [{ kind: "taunt-immune" }],
  },
  {
    id: "battle-axe",
    name: "Battle Axe",
    description: "Attacks cleave: every enemy within 1 cell of the target takes 50% of the hit.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "cleave", fraction: 0.5, radiusUnits: 10 }],
  },
  {
    id: "daedalus-edge",
    name: "Daedalus Edge",
    description: "+5% crit chance, and crits deal ×2.25 instead of ×1.75.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [
      { target: { kind: "crit-chance" }, kind: "flat", value: 0.05 },
      { target: { kind: "crit-multiplier" }, kind: "flat", value: 0.5 },
    ],
  },
  {
    id: "quicksilver-boots",
    name: "Quicksilver Boots",
    description: "After any dash, leap or blink, +60% attack speed for 2 s.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "quicksilver", attackSpeedBonus: 0.6, durationTicks: 60 }],
  },
  {
    id: "null-talisman",
    name: "Null Talisman",
    description: "Enemies within 2 cells of the holder can't trigger their gems.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "null-talisman", radiusUnits: 20 }],
  },
  {
    id: "aegis",
    name: "Aegis",
    description: "Revive once at 20% HP.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "revive", hpFraction: 0.2 }],
  },
  {
    id: "kingmaker-banner",
    name: "Kingmaker Banner",
    description: "Every combo your team detonates gives every ally +4% attack speed for the rest of the fight.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "combo-rally", attackSpeedPerCombo: 0.04 }],
  },
  {
    id: "worldbreaker",
    name: "Worldbreaker",
    description: "Combos this hero detonates also hit every enemy within 2 cells.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "combo-splash", radiusUnits: 20 }],
  },
  {
    id: "prism-of-three",
    name: "Prism of Three",
    description: "This hero's hits count as Might, Arcana and Cunning at once, so they detonate any condition an ally applied.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "prism" }],
  },
  {
    id: "crown-of-echoes",
    name: "Crown of Echoes",
    description: "Multistrike and Multicast repeats are at full strength.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "crown-of-echoes" }],
  },
  {
    id: "blood-pact",
    name: "Blood Pact",
    description:
      "The ability and ultimate cost 6% of current HP instead of cooldown or mana, at most once a second each. Below 30% HP neither can be cast.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "blood-pact", hpFraction: 0.06, minHpFraction: 0.3, floorTicks: 30 }],
  },
  {
    id: "spellblade-hilt",
    name: "Spellblade Hilt",
    description: "Spells count as attacks for on-hit effects: every spell hit can cleave, Burn, siphon or throw lightning.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "spellblade-hilt" }],
  },
  {
    id: "storm-gauntlet",
    name: "Storm Gauntlet",
    description: "Attacks have a 25% chance to throw chain lightning: 80 Arcana damage, jumping to up to 4 enemies.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "chain-lightning", chance: 0.25, damage: 80, bounces: 4, rangeUnits: 25, school: "arcana" }],
  },
  {
    id: "essence-siphon",
    name: "Essence Siphon",
    description: "Each attack steals 3% attack speed from its target for 8 s.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "essence-siphon", steal: 0.03, durationTicks: 240 }],
  },
  {
    id: "thorn-mail",
    name: "Thorn Mail",
    description: "When an attack hits the holder, the attacker takes 10 + 1.5% of the holder's max HP back.",
    category: "item",
    rarity: "rare",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "thorns", amount: 10, maxHpFraction: 0.015, attacksOnly: true }],
  },
  {
    id: "voidheart",
    name: "Voidheart",
    description: "Enemies this hero kills burst 0.3 s later, dealing a quarter of their max HP to every enemy within 1.5 cells. The bodies are used up.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "voidheart", abilityId: voidheartBlast.id, delayTicks: 9 }],
  },
  {
    id: "infinity-band",
    name: "Infinity Band",
    description: "Trigger gems on this hero recharge twice as fast.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "infinity-band", rechargeMultiplier: 0.5 }],
  },
  {
    id: "berserkers-collar",
    name: "Berserker's Collar",
    description: "+50% attack speed. Downside: the holder can't be healed.",
    category: "item",
    rarity: "rare",
    cursed: true,
    maxStacks: 1,
    statModifiers: [{ target: { kind: "basic-attack-cooldown" }, kind: "percent", value: 0.5 }],
    grantsPassives: [{ kind: "unhealable" }],
  },
  {
    id: "unstable-core",
    name: "Unstable Core",
    description: "The ability and ultimate each cast a second time 0.3 s later, at full strength. Downside: each cast costs 5% of max HP. This can't take the holder below 1 HP.",
    category: "item",
    rarity: "legendary",
    cursed: true,
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "unstable-core", hpFraction: 0.05, delayTicks: 9 }],
  },
  {
    id: "the-unbound",
    name: "The Unbound",
    description: "+1 gem socket in the ability and the ultimate. Taking it off sends the extra gems back to the stash.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    extraGemSockets: 1,
  },
  {
    id: "heart-of-the-swarm",
    name: "Heart of the Swarm",
    description: "Units this hero summons carry copies of its other items.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "heart-of-the-swarm" }],
  },
  {
    id: "obsidian-mirror",
    name: "Obsidian Mirror",
    description: "The first enemy ultimate cast at the holder is reflected: the holder casts it back at the caster instead. Works once per fight.",
    category: "item",
    rarity: "legendary",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "obsidian-mirror" }],
  },
];
