import type { AbilityTag, UpgradeDefinition } from "@jev-game/game";

const EVERY_SIGNATURE: AbilityTag[] = ["area", "self", "target", "projectile", "line", "dash", "delayed", "zone", "heal", "summon", "link", "channel"];

const DAMAGING: AbilityTag[] = ["area", "target", "projectile", "line", "dash", "delayed"];

export const runes: UpgradeDefinition[] = [
  {
    id: "rune-chain",
    name: "Chain",
    description: "The signature also hits 2 more nearby enemies at 45%.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "chain", extraTargets: 2, fraction: 0.45, rangeUnits: 25 },
    runeFits: ["target", "projectile", "link"],
  },
  {
    id: "rune-echo",
    name: "Echo",
    description: "The signature casts again 1 s later at 35%.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "echo", fraction: 0.35, delayTicks: 30 },
    runeFits: ["area", "self", "target", "projectile", "line", "dash", "delayed", "zone", "heal"],
  },
  {
    id: "rune-widen",
    name: "Widen",
    description: "The signature's area is 50% bigger.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "widen", radiusMultiplier: 1.5 },
    runeFits: ["area"],
  },
  {
    id: "rune-primer-staggered",
    name: "Primer: Staggered",
    description: "The signature also Staggers what it hits.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "primer", condition: "staggered" },
    runeFits: DAMAGING,
  },
  {
    id: "rune-leech",
    name: "Leech",
    description: "The signature heals its caster for 25% of the damage it deals.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "leech", fraction: 0.25 },
    runeFits: ["target", "projectile", "line", "dash", "delayed"],
  },
  {
    id: "rune-retaliate",
    name: "Retaliate",
    description: "The signature also casts for free at 40% every time its hero loses 25% of max HP.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "retaliate", fraction: 0.4, hpLossFraction: 0.25 },
    runeFits: ["area", "self", "heal"],
  },
  {
    id: "rune-primer-brittle",
    name: "Primer: Brittle",
    description: "The signature also makes what it hits Brittle.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "primer", condition: "brittle" },
    runeFits: DAMAGING,
  },
  {
    id: "rune-primer-disoriented",
    name: "Primer: Disoriented",
    description: "The signature also Disorients what it hits.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "primer", condition: "disoriented" },
    runeFits: DAMAGING,
  },
  {
    id: "rune-fork",
    name: "Fork",
    description: "When the signature's projectile hits its first enemy, it splits into 2 more that fly off at an angle and deal 60%.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "fork", branches: 2, fraction: 0.6, angleDegrees: 35, lengthUnits: 45 },
    runeFits: ["projectile"],
  },
  {
    id: "rune-twincast",
    name: "Twincast",
    description: "30% chance that the signature casts a second time at full strength. The second cast can't apply or detonate conditions.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "twincast", chance: 0.3 },
    runeFits: EVERY_SIGNATURE,
  },
  {
    id: "rune-split",
    name: "Split",
    description: "The signature summons 1 more unit and allows 1 more at once, but every summon from it has 30% less HP and damage.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "split", extraSummons: 1, strength: 0.7 },
    runeFits: ["summon"],
  },
  {
    id: "rune-empower",
    name: "Empower",
    description: "Summons from the signature have 40% more HP and damage.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "empower", strength: 1.4 },
    runeFits: ["summon"],
  },
  {
    id: "rune-linger",
    name: "Linger",
    description:
      "The signature's area stays for 3 s and repeats 25% of its damage and healing every second. If the signature already leaves ground behind, that ground lasts 3 s longer. Whirlwind spins 1 s longer.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "linger", durationTicks: 90, periodTicks: 30, fraction: 0.25, channelTicks: 30 },
    runeFits: ["area", "zone", "channel"],
  },
  {
    id: "rune-opener",
    name: "Opener",
    description: "The signature casts once for free about 2 s into every fight. That free cast can't apply or detonate conditions.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "opener", atTick: 60 },
    runeFits: EVERY_SIGNATURE,
  },
  {
    id: "rune-last-word",
    name: "Last Word",
    description: "When its hero dies, the signature casts once for free from where the hero fell. That cast can't apply or detonate conditions.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "last-word" },
    runeFits: EVERY_SIGNATURE,
  },
  {
    id: "rune-tandem",
    name: "Tandem",
    description:
      "Whenever an ally detonates a combo, the signature casts for free at 50%, at most once every 3 s. That cast can't apply or detonate conditions.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "tandem", fraction: 0.5, cooldownTicks: 90 },
    runeFits: EVERY_SIGNATURE,
  },
  {
    id: "rune-resonance",
    name: "Resonance",
    description:
      "The signature's hits count as Might, Arcana and Cunning at once, so they can detonate any condition, including ones its own hero applied.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "resonance" },
    runeFits: EVERY_SIGNATURE,
  },
  {
    id: "rune-haste",
    name: "Haste",
    description: "The signature costs 25% less mana.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "haste", manaCostMultiplier: 0.75 },
    runeFits: EVERY_SIGNATURE,
  },
  {
    id: "rune-overcharge",
    name: "Overcharge",
    description: "The signature is 75% stronger. Downside: each cast costs its hero 8% of current HP.",
    category: "rune",
    maxStacks: 1,
    statModifiers: [],
    rune: { kind: "overcharge", effectMultiplier: 1.75, hpCostFraction: 0.08 },
    runeFits: EVERY_SIGNATURE,
  },
];
