import type { AbilityDefinition, HeroDefinition, UpgradeDefinition } from "@jev-game/game";

export const duskStrike: AbilityDefinition = {
  id: "dusk-strike",
  name: "Dusk Strike",
  hitType: "attack",
  tags: ["target"],
  cooldownTicks: 34,
  targetPolicy: "nearest-enemy",
  range: 10,
  effects: [{ kind: "damage", amount: 73, maxAmount: 90 }],
};

export const flickerStrike: AbilityDefinition = {
  id: "flicker-strike",
  name: "Flicker Strike",
  description:
    "Pounces on the weakest enemy and strikes, then on a different enemy within 3 cells (up to 6 for one she hasn't struck yet), 3 times, 0.2 s apart. Each strike is a full attack, and the last one Disorients.",
  hitType: "attack",
  tags: ["strike", "dash", "target"],
  cooldownTicks: 180,
  initialCooldownTicks: 90,
  targetPolicy: "lowest-hp-enemy",
  range: 999,
  effects: [{ kind: "strike", scale: 1 }],
  dash: {
    hops: 3,
    periodTicks: 6,
    hopRangeUnits: 30,
    finalEffects: [{ kind: "apply-condition", condition: "disoriented" }],
  },
};

export const thousandCuts: AbilityDefinition = {
  id: "thousand-cuts",
  name: "Thousand Cuts",
  description:
    "Can't be targeted while she makes 8 strikes across every enemy in 1.6 s, then lands behind the weakest enemy hero. Each strike is a full attack.",
  hitType: "attack",
  tags: ["strike", "dash", "target"],
  cooldownTicks: 30,
  manaCost: 200,
  targetPolicy: "nearest-enemy",
  range: 999,
  effects: [{ kind: "strike", scale: 1 }],
  dash: { hops: 8, periodTicks: 6, hopRangeUnits: 0, untargetable: true, endBehindLowestHero: true },
};

export const duskblade: HeroDefinition = {
  id: "duskblade",
  name: "Vesper",
  title: "Finds the weakest and finishes it",
  school: "cunning",
  archetype: "dive",
  appliesCondition: "disoriented",
  maxHp: 1550,
  armor: 0.1,
  moveSpeedUnitsPerSecond: 25,
  manaPerAttack: 21,
  critChance: 0.2,
  basicAttackId: duskStrike.id,
  abilityId: flickerStrike.id,
  ultimateId: thousandCuts.id,
  passives: [
    {
      kind: "stacks",
      key: "frenzy",
      name: "Frenzy",
      description: "Each crit adds a Frenzy charge, up to 5, and each gives +8% attack speed. Flicker Strike spends them all for 1 more strike each.",
      gains: [{ on: "crit", amount: 1 }],
      max: 5,
      attackSpeedPerStack: 0.08,
      spentBy: flickerStrike.id,
      extraHopsPerStack: 1,
    },
  ],
};

export const duskbladeAbilities: AbilityDefinition[] = [duskStrike, flickerStrike, thousandCuts];

export const duskbladeLevels: UpgradeDefinition[] = [
  {
    id: "dusk-longer-chain",
    name: "Longer Chain",
    description: "Flicker Strike pounces 2 more times.",
    category: "level",
    heroId: duskblade.id,
    level: 2,
    path: "left",
    maxStacks: 1,
    statModifiers: [],
    abilityChanges: [{ abilityId: flickerStrike.id, addHops: 2 }],
  },
  {
    id: "dusk-rhythm",
    name: "Rhythm",
    description: "Each strike in a Flicker Strike chain has 10% more crit chance than the one before.",
    category: "level",
    heroId: duskblade.id,
    level: 2,
    path: "right",
    maxStacks: 1,
    statModifiers: [],
    abilityChanges: [{ abilityId: flickerStrike.id, patchDash: { critBonusPerHop: 0.1 } }],
  },
  {
    id: "dusk-shadow-clone",
    name: "Shadow Clone",
    description: "A shade repeats every Flicker Strike 0.5 s later at 50%.",
    category: "level",
    heroId: duskblade.id,
    level: 3,
    path: "left",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "shadow-clone", abilityId: flickerStrike.id, delayTicks: 15, fraction: 0.5 }],
  },
  {
    id: "dusk-executioner",
    name: "Executioner",
    description: "A kill with Flicker Strike or Thousand Cuts makes Flicker Strike ready again.",
    category: "level",
    heroId: duskblade.id,
    level: 3,
    path: "right",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "executioner", fromAbilityIds: [flickerStrike.id, thousandCuts.id], resetsAbilityId: flickerStrike.id }],
  },
  {
    id: "dusk-death-blossom",
    name: "Death Blossom",
    description: "Every Thousand Cuts strike also hits every enemy within 1 cell of its target.",
    category: "level",
    heroId: duskblade.id,
    level: 4,
    path: "left",
    maxStacks: 1,
    statModifiers: [],
    abilityChanges: [{ abilityId: thousandCuts.id, patchDash: { splashRadiusUnits: 10 } }],
  },
  {
    id: "dusk-mark-for-death",
    name: "Mark for Death",
    description:
      "Thousand Cuts only strikes the weakest enemy hero, and each strike makes it take 10% more damage for 3 s. When it dies, the rest go to the next weakest.",
    category: "level",
    heroId: duskblade.id,
    level: 4,
    path: "right",
    maxStacks: 1,
    statModifiers: [],
    abilityChanges: [{ abilityId: thousandCuts.id, patchDash: { markPerStrike: 0.1 } }],
  },
];
