import type { AbilityDefinition, HeroDefinition, UpgradeDefinition } from "@jev-game/game";

export const spiteBolt: AbilityDefinition = {
  id: "spite-bolt",
  name: "Spite Bolt",
  hitType: "attack",
  cooldownTicks: 55,
  targetPolicy: "nearest-enemy",
  range: 35,
  effects: [{ kind: "damage", amount: 48, maxAmount: 59 }],
  tags: ["projectile", "target"],
};

export const sharedFate: AbilityDefinition = {
  id: "shared-fate",
  name: "Shared Fate",
  hitType: "spell",
  description: "Binds up to 4 enemies within 4 cells of the densest group for 5 s. Half the damage any of them takes is dealt to the others.",
  cooldownTicks: 30,
  manaCost: 70,
  targetPolicy: "densest-enemy-cluster",
  range: 50,
  area: { kind: "circle", center: "target", radiusUnits: 40 },
  maxTargets: 4,
  effects: [{ kind: "bind", fraction: 0.5, durationTicks: 150 }],
  canCrit: false,
  tags: ["area", "link"],
};

export const hex: AbilityDefinition = {
  id: "hex",
  name: "Hex",
  hitType: "spell",
  description: "Turns the enemy with the most mana into a harmless critter for 2 s and leaves it Disoriented.",
  cooldownTicks: 270,
  targetPolicy: "highest-mana-enemy",
  range: 45,
  effects: [
    { kind: "control", control: "hexed", durationTicks: 60 },
    { kind: "apply-condition", condition: "disoriented" },
  ],
  tags: ["target"],
};

export const hexbinder: HeroDefinition = {
  id: "hexbinder",
  name: "Moira",
  title: "Ties your fates together",
  school: "arcana",
  archetype: "blight",
  appliesCondition: "disoriented",
  maxHp: 1500,
  armor: 0.05,
  moveSpeedUnitsPerSecond: 17,
  critChance: 0.05,
  manaPerAttack: 21,
  basicAttackId: spiteBolt.id,
  abilityId: hex.id,
  ultimateId: sharedFate.id,
  passives: [
    {
      kind: "stacks",
      key: "threads",
      name: "Weaver",
      description: "Gains a Thread for every 75 damage a hexed or bound enemy takes. At 10 Threads, her next Hex also hits the 2 enemies nearest its target.",
      gains: [{ on: "bound-damage", amount: 1, per: 75 }],
      max: 10,
      attackSpeedPerStack: 0,
      spentBy: hex.id,
      atMax: { extraTargets: { count: 2, rangeUnits: 45 } },
    },
  ],
};

export const hexbinderAbilities: AbilityDefinition[] = [spiteBolt, sharedFate, hex];

export const hexbinderLevels: UpgradeDefinition[] = [
  {
    id: "hexbinder-wider-net",
    name: "Wider Net",
    description: "Shared Fate binds up to 6 enemies within 6 cells.",
    category: "level",
    heroId: hexbinder.id,
    level: 2,
    path: "left",
    maxStacks: 1,
    statModifiers: [],
    abilityChanges: [{ abilityId: sharedFate.id, setMaxTargets: 6, setArea: { kind: "circle", center: "target", radiusUnits: 60 } }],
  },
  {
    id: "hexbinder-long-bond",
    name: "Long Bond",
    description: "Shared Fate lasts 3 s longer.",
    category: "level",
    heroId: hexbinder.id,
    level: 2,
    path: "right",
    maxStacks: 1,
    statModifiers: [],
    abilityChanges: [{ abilityId: sharedFate.id, patchBind: { durationTicks: 240 } }],
  },
  {
    id: "hexbinder-death-knell",
    name: "Death Knell",
    description: "When a bound enemy dies, the others take 10% of its max HP.",
    category: "level",
    heroId: hexbinder.id,
    level: 3,
    path: "left",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "death-knell", maxHpFraction: 0.1 }],
  },
  {
    id: "hexbinder-hex-bolt",
    name: "Hex Bolt",
    description: "Hex jumps to a second enemy within 3 cells.",
    category: "level",
    heroId: hexbinder.id,
    level: 3,
    path: "right",
    maxStacks: 1,
    statModifiers: [],
    abilityChanges: [{ abilityId: hex.id, setBounces: { count: 1, rangeUnits: 30 } }],
  },
  {
    id: "hexbinder-ill-omen",
    name: "Ill Omen",
    description: "A combo detonated on one bound enemy detonates on every enemy bound with it.",
    category: "level",
    heroId: hexbinder.id,
    level: 4,
    path: "left",
    maxStacks: 1,
    statModifiers: [],
    grantsPassives: [{ kind: "ill-omen" }],
  },
  {
    id: "hexbinder-puppeteer",
    name: "Puppeteer",
    description: "Shared Fate costs 50 more mana, and for its first 2.5 s the enemies it binds can only attack each other.",
    category: "level",
    heroId: hexbinder.id,
    level: 4,
    path: "right",
    maxStacks: 1,
    statModifiers: [{ target: { kind: "ability-mana-cost", abilityId: sharedFate.id }, kind: "flat", value: 50 }],
    abilityChanges: [{ abilityId: sharedFate.id, patchBind: { puppetTicks: 75 } }],
  },
];
